urban/routes/web.php
<?php

// All auth routes
Auth::routes(['verify' => true]);

// Admin auth routes
Route::get('/admin/login', [
    'uses' => 'AdminController@login',
    'as' => 'admin.login'
]);

/**
 * All public routes
 * @var null
 */

// Landing page
Route::get('/', [
    'uses' => 'PublicViewsController@index',
    'as' => 'home'
]);

// Shop page
Route::get('/shop', [
    'uses' => 'PublicViewsController@shop',
    'as' => 'shop'
]);

// Single product page
Route::get('/product/{slug}', [
    'uses' => 'PublicViewsController@product',
    'as' => 'product'
]);

// About page
Route::get('/about', [
    'uses' => 'PublicViewsController@about',
    'as' => 'about'
]);

// Blog page
Route::get('/blog', [
    'uses' => 'PublicViewsController@blog',
    'as' => 'blog'
]);

// Blog post page
Route::get('/blog/{slug}', [
    'uses' => 'PublicViewsController@post',
    'as' => 'blog.post'
]);

// Blog post comment store
Route::post('/blog/comment/store/{id}', [
    'uses' => 'CommentController@store',
    'as' => 'blog.comment.store'
]);

// Contact page
Route::get('/contact', [
    'uses' => 'PublicViewsController@contact',
    'as' => 'contact'
]);

// Message store controller
Route::post('/contact/store', [
    'uses' => 'MessageController@store',
    'as' => 'contact.store'
]);

// Shopping cart route group
Route::group(['prefix' => 'cart'], function() {

    // Shopping cart page
    Route::get('/', [
        'uses' => 'PublicViewsController@cart',
        'as' => 'cart'
    ]);

    // Shopping cart page
    Route::post('/add/{id}', [
        'uses' => 'CartController@store',
        'as' => 'cart.add'
    ]);

    // Shopping cart page
    Route::get('/remove/{id}', [
        'uses' => 'CartController@destroy',
        'as' => 'cart.remove'
    ]);

    // Shopping cart page
    Route::post('/update/{id}', [
        'uses' => 'CartController@update',
        'as' => 'cart.update'
    ]);
});

// Shopping wishlist route group
Route::group(['prefix' => 'wishlist'], function() {

    // Shopping wishlist page
    Route::get('/', [
        'uses' => 'PublicViewsController@wishlist',
        'as' => 'wishlist'
    ]);

    // Shopping wishlist page
    Route::post('/add/{id}', [
        'uses' => 'WishListController@store',
        'as' => 'wishlist.add'
    ]);

    Route::get('/add_cart/{id}', [
        'uses' => 'WishListController@addToCart',
        'as' => 'wishlist.add.cart'
    ]);

    // Shopping wishlist page
    Route::get('/remove/{id}', [
        'uses' => 'WishListController@destroy',
        'as' => 'wishlist.remove'
    ]);
});

// Coupons
Route::group(['prefix' => 'coupon'], function() {

    // Add coupon
    Route::post('/add', [
        'uses' => 'CartController@coupon_add',
        'as' => 'coupon.add'
    ]);

    Route::get('/remove', [
        'uses' => 'CartController@coupon_remove',
        'as' => 'coupon.remove'
    ]);
});

// Checkout routes
Route::group(['prefix' => 'checkout', 'middleware' => 'auth'], function() {

    // Checkout page
    Route::get('/', [
        'uses' => 'PublicViewsController@checkout',
        'as' => 'checkout'
    ]);

    /* Payment processing */
    Route::post('/pay', [
        'uses' => 'PaymentsController@store',
        'as' => 'checkout.pay'
    ]);
});

// Newsletter subscription
Route::post('/subscribe', [
    'uses' => 'NewsletterController@store',
    'as' => 'subscribe'
]);

// Member auth routes
Route::group(['prefix' => 'account', 'middleware' => 'verified'], function() {

    // Customer accounts
    Route::get('/', [
        'uses' => 'ProfileController@index',
        'as' => 'account'
    ]);

    // Customer accounts
    Route::get('/details', [
        'uses' => 'ProfileController@details',
        'as' => 'account.details'
    ]);

    Route::post('/update/{id}', [
        'uses' => 'ProfileController@update',
        'as' => 'account.update'
    ]);

    // Customer account addresses
    Route::get('/addresses', [
        'uses' => 'ProfileController@addresses',
        'as' => 'account.addresses'
    ]);

    // Customer account wishlist
    Route::get('/wishlist', [
        'uses' => 'ProfileController@wishlist',
        'as' => 'account.wishlist'
    ]);

    // Customer accounts
    Route::get('/orders', [
        'uses' => 'ProfileController@orders',
        'as' => 'account.orders'
    ]);
});

Route::get('/thankyou', [
    'uses' => 'PublicViewsController@thankyou',
    'as' => 'thankyou'
]);

/* Admin routes */
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {

    // Admin dashboard page
    Route::get('/', [
        'uses' => 'AdminController@index',
        'as' => 'admin'
    ]);

    // Admin log
    Route::get('/log', [
        'uses' => 'AdminController@log',
        'as' => 'admin.log'
    ]);

    // Admin notifications
    Route::get('/notifications', [
        'uses' => 'AdminController@notifications',
        'as' => 'admin.notifications'
    ]);

    // Admin categories routes
    Route::group(['prefix' => 'categories'], function() {

        // Admin categories store to database
        Route::post('/store', [
            'uses' => 'CategoryController@store',
            'as' => 'admin.categories.store'
        ]);
    });

    // Admin tags routes
    Route::group(['prefix' => 'tags'], function() {

        // Admin tags store to database
        Route::post('/store', [
            'uses' => 'TagController@store',
            'as' => 'admin.tags.store'
        ]);
    });

    // Admin users routes
    Route::group(['prefix' => 'users'], function() {

        // Admin users list
        Route::get('/', [
            'uses' => 'UsersController@index',
            'as' => 'admin.users'
        ]);

        // Admin add new users
        Route::get('/create', [
            'uses' => 'UsersController@create',
            'as' => 'admin.users.create'
        ]);

        // Admin users list
        Route::get('/verify/{id}', [
            'uses' => 'UsersController@verify',
            'as' => 'admin.users.verify'
        ]);

        // Admin add new users to database
        Route::post('/store', [
            'uses' => 'UsersController@store',
            'as' => 'admin.users.store'
        ]);

        // Admin user profile
        Route::get('/profile/{slug}', [
            'uses' => 'UsersController@profile',
            'as' => 'admin.users.profile'
        ]);

        // Admin user profile
        Route::post('/update/account/{slug}', [
            'uses' => 'UsersController@update_account',
            'as' => 'admin.users.update.account'
        ]);

        // Admin user profile
        Route::post('/update/profile/{slug}', [
            'uses' => 'UsersController@update',
            'as' => 'admin.users.update.profile'
        ]);

        // Admin user activities - reserved only for Administrators
        Route::get('/activities/{slug}', [
            'uses' => 'UsersController@activities',
            'as' => 'admin.users.activities'
        ]);

        // Admin user edit
        Route::get('/edit/{slug}', [
            'uses' => 'UsersController@edit',
            'as' => 'admin.users.edit'
        ]);
    });

    // Admin sales routes
    Route::group(['prefix' => 'sales'], function() {

        // Admin orders routes
        Route::group(['prefix' => 'orders'], function() {

            // Admin orders list
            Route::get('/', [
                'uses' => 'OrderController@index',
                'as' => 'admin.sales.orders'
            ]);

            // Admin order show
            Route::get('/{id}', [
                'uses' => 'OrderController@show',
                'as' => 'admin.sales.orders.show'
            ]);
        });

        // Admin products list
        Route::get('/coupons', [
            'uses' => 'SalesController@coupons',
            'as' => 'admin.sales.coupons'
        ]);
    });

    // Admin products routes
    Route::group(['prefix' => 'products'], function() {

        // Admin products list
        Route::get('/', [
            'uses' => 'ProductController@index',
            'as' => 'admin.products'
        ]);

        // Admin add new products
        Route::get('/create', [
            'uses' => 'ProductController@create',
            'as' => 'admin.products.create'
        ]);

        // Admin add new products
        Route::post('/store', [
            'uses' => 'ProductController@store',
            'as' => 'admin.products.store'
        ]);

        // Admin edit products
        Route::get('/edit/{id}', [
            'uses' => 'ProductController@edit',
            'as' => 'admin.products.edit'
        ]);

        // Admin edit products
        Route::post('/update/{id}', [
            'uses' => 'ProductController@update',
            'as' => 'admin.products.update'
        ]);

        // Admin products categories
        Route::group(['prefix' => 'categories'], function() {

            // Admin products categories list
            Route::get('/{from}', [
                'uses' => 'CategoryController@index',
                'as' => 'admin.products.categories'
            ]);
        });

        // Admin products tags
        Route::group(['prefix' => 'tags'], function() {

            // Admin products tags list
            Route::get('/{from}', [
                'uses' => 'TagController@index',
                'as' => 'admin.products.tags'
            ]);
        });

        // Admin products brands
        Route::group(['prefix' => 'brands'], function() {

            // Admin products brands list
            Route::get('/', [
                'uses' => 'BrandController@index',
                'as' => 'admin.products.brands'
            ]);

            Route::post('/store', [
                'uses' => 'BrandController@store',
                'as' => 'admin.products.brands.store'
            ]);
        });

        // Admin products attributes
        Route::group(['prefix' => 'attributes'], function() {

urban/app/Post.php
<?php

namespace Urban;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model {

    use SoftDeletes;

    public $with = [
        //
    ];

    protected $dates = [
        'deteled_at'
    ];

    protected $fillable = [
        'title',
        'content',
        'user_id',
        'media_id',
        'excerpt',
        'slug',
        'user_id',
        'discussion',
        'visibility',
        'status'
    ];

    public function categories() {
        return $this->belongsToMany('Urban\Category');
    }

    public function tags() {
        return $this->belongsToMany('Urban\Tag');
    }

    public function media() {
        return $this->belongsTo('Urban\Media');
    }

    public function comments() {
        return $this->hasMany('Urban\Comment');
    }

    public function user() {
        return $this->belongsTo('Urban\User');
    }
}

urban/app/User.php
<?php

namespace Urban;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail {

    use Notifiable;

    public $with = [
        'profile',
        'role'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
        'admin',
        'subscription',
        'slug'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function profile() {
        return $this->hasOne('Urban\Profile', 'user_id');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function role() {
        return $this->belongsTo('Urban\Role', 'role_id');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function medias() {
        return $this->hasOne('Urban\Media', 'user_id');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function activities() {
        return $this->hasMany('Urban\Activity', 'user_id');
    }

    /**
     * [user description]
     * @return [type] [description]
     */
    public function messages() {
        return $this->hasMany('Urban\Message', 'user_id');
    }

    /**
     * [products description]
     * @return [type] [description]
     */
    public function products() {
        return $this->hasMany('Urban\Product', 'user_id');
    }

    /**
     * [products description]
     * @return [type] [description]
     */
    public function reviews() {
        return $this->hasMany('Urban\Review');
    }

    /**
     * [orders description]
     * @return [type] [description]
     */
    public function orders() {
        return $this->hasMany('Urban\Order');
    }

    /**
     * [products description]
     * @return [type] [description]
     */
    public function posts() {
        return $this->hasMany('Urban\Post');
    }

    /**
     * [products description]
     * @return [type] [description]
     */
    public function comments() {
        return $this->hasMany('Urban\Comment');
    }

    /**
     * [subscription description]
     * @return [type] [description]
     */
    public function subscription() {
        return $this->hasOne('Urban\Newsletter');
    }

    /**
     * [subscription description]
     * @return [type] [description]
     */
    public function addresses() {
        return $this->hasMany('Urban\Address');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function getNameAttribute($name) {
        return ucwords($name);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function getCreatedAtAttribute($date) {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public function getUpdatedAtAttribute($date) {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }
}

urban/resources/views/admin/posts/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<form class="d-inline" action="{!! route('admin.posts.update') !!}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="heading mb-5">Add New Blog Post</h6>
                    <div class="form-group">
                        <label for="title">Post Title</label>
                        <input type="text" name="title" id="title" class="form-control mb-5" placeholder="Post Title" value="{{ $post->title }}" required>

                        @if ($errors->has('title'))
                            <span class="text-danger form-text" role="alert">
                                <small><strong>{{ $errors->first('title') }}</strong></small>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <textarea name="content" class="form-control" id="post_content">{{ $post->content }}</textarea>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <label for="excerpt">Excerpt</label>
                            <textarea id="excerpt" name="excerpt" class="form-control" placeholder="Excerpt">{{ $post->excerpt }}</textarea>

                            @if ($errors->has('excerpt'))
                                <span class="text-danger form-text" role="alert">
                                    <small><strong>{{ $errors->first('excerpt') }}</strong></small>
                                </span>
                            @endif

                            <span class="text-muted form-text">
                                <small>
                                    Excerpts are optional hand-crafted summaries of your content that can be used in your theme. <a href="#">Learn more about manual excerpts</a>.
                                </small>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <label for="discussion">Discussion</label>
                            <div class="custom-control custom-checkbox mb-5">
                                <input type="checkbox" class="custom-control-input"
                                @if ($post->discussion)
                                    checked
                                @endif
                                id="discussion" value="1">
                                <label class="custom-control-label" for="discussion"> <strong>Allow comments</strong></label>
                            </div>
                            <label for="user_id">Author</label>
                            <select id="user_id" class="custom-select" name="user_id">
                                @foreach ($users as $user)
                                    <option
                                        @if ($post->user_id == $user->id)
                                            selected
                                        @endif
                                        value="{{ $user->id }}"
                                        >{{ $user->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h6 class="heading mb-3">Publish</h6>
                    <div class="row">
                        <div class="col mb-3">
                            <div class="status">
                                <label>Status</label>
                               <div class="custom-control custom-radio mb-3">
                                    <input type="radio" id="status1"  @if ($post->status) checked @endif name="status" class="custom-control-input">
                                    <label class="custom-control-label" for="status1"> <strong>Publish</strong></label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="status2" name="status" @if (!$post->status) checked @endif class="custom-control-input">
                                    <label class="custom-control-label" for="status2"> <strong>Draft</strong></label>
                                </div>
                            </div>
                        </div>
                        <div class="col mb-3">
                            <label>Visibilty</label>
                            <div class="custom-control custom-radio mb-3">
                                <input type="radio" id="visibility1" @if ($post->visibility) checked @endif name="visibility" class="custom-control-input">
                                <label class="custom-control-label" for="visibility1"> <strong>Public</strong></label>
                            </div>
                            <div class="custom-control custom-radio">
                                <input type="radio" id="visibility2" @if (!$post->visibility) checked @endif name="visibility" class="custom-control-input">
                                <label class="custom-control-label" for="visibility2"> <strong>Private</strong></label>
                            </div>
                        </div>
                        <div class="col mb-3">
                            <label>Post published</label>
                            <div>
                                <span class="badge badge-primary">
                                    {{ $post->created_at->format("F j, Y") }}
                                </span>
                            </div>
                        </div>
                        <div class="col mb-3">
                            <label>Post last updated</label>
                            <div>
                                <span class="badge badge-primary">
                                    {{ $post->updated_at->format("F j, Y") }}
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="text-right mt-4 clearfix">
                        <button type="submit" class="btn btn-primary">Publish</button>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="heading">Featured Image</h6>
                    <div class="featured-img">
                        <a href="#" data-toggle="modal" data-target="#PostImageModal">
                            Set featured image
                        </a>
                    </div>
                </div>
            </div>
            <!-- Media modal -->
            <div class="modal fade" id="PostImageModal" tabindex="-1" role="dialog" aria-labelledby="PostImageModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="PostImageModalLabel">Featured Image</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            @if (count($medias) > 0)
                                <select class="image-picker show-html" id="post-image" name="medias[]">
                                    @foreach ($medias as $media)
                                        <option
                                            data-img-src="{{ asset($media->url) }}"
                                            value="{{ $media->id }}"
                                            @if ($post->media->id == $media->id)
                                                selected
                                            @endif>
                                            {{ $media->name }}
                                        </option>
                                    @endforeach
                                </select>
                                <hr>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="images" multiple="multiple" name="image">
                                    <label class="custom-file-label" for="images">Choose files</label>
                                </div>
                            @else
                                <p>
                                    No media items found.
                                </p>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="images" name="image">
                                    <label class="custom-file-label" for="images">Choose files</label>
                                </div>
                            @endif
                        </div>
                        <div class="modal-footer">
                            {{-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> --}}
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Set Featured</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- New Category -->
            <vue-newcategory to="{{ __('post') }}" @if ($edit) :categories="{{ $post->categories }}" @endif></vue-newcategory>
            <!-- New Tag -->
            <vue-newtag to="{{ __('post') }}" @if ($edit) :tags="{{ $post->tags }}" @endif></vue-newtag>
        </div>
    </div>
</form>
@endsection

@section('new-post-js')
    <script>
        tinymce.init({
            selector: '#post_content',
            themes: "modern",
            menubar: false,
            mobile: {
                theme: 'mobile',
                plugins: [ 'autosave', 'lists', 'autolink' ]
            }
        });
        
        // Image picker initialization
        $("#post-image").imagepicker();
    </script>
@endsection